/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.henriquemcc.simulacao.detector.falhas.consenso

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
}
